Test

diff --git a/.github/workflows/Sample.yml b/.github/workflows/Sample.yml
--- a/.github/workflows/Sample.yml
+++ b/.github/workflows/Sample.yml
@@ -30,6 +30,15 @@ jobs:
           ls -l 
           python -u EnvVariableList.py
       
+      - name: Checking Overall Status of Run
+        shell: bash
+        if: ${{ always() && (env.FAILED_ACR_DOCKERFILES != '' || env.FAILED_ECR_DOCKERFILES != '') }}
+        run: |
+          echo "❌ FAILED : Dockerfiles failed during the build and push process."
+          echo "Failed ACR Dockerfiles: $FAILED_ACR_DOCKERFILES"
+          echo "Failed ECR Dockerfiles: $FAILED_ECR_DOCKERFILES"
+          exit 1
+      
       - name: Testing If Condition
         shell: bash
         if: ${{ env.FAILED_ECR_DOCKERFILES != '[]' }} 
